"use client"
import Navbar from '@/views/appbars/Navbar'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Footer from '@/views/appbars/Footer'
import { QueryClient, QueryClientProvider } from 'react-query';
import {Provider} from 'react-redux'
import store from '@/store/store'
import {usePathname} from 'next/navigation'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'DailyShop',
  description: 'Generated by beta technologies',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const queryClient = new QueryClient();
  const pathname = usePathname()
  return (
    <html lang="en">
      <Provider store={store}>
        <QueryClientProvider client={queryClient}>
        <body className={inter.className}>
          {
            pathname ==='/cart' ? '' : <Navbar/>
          }
          <div>
            {children}
          </div>
          {
          pathname ==='/cart' ? '' : <Footer/>
          }
        </body>
        </QueryClientProvider>
      </Provider>
    </html>
  )
}
